/**
 * Secure Maintenance Mode Utility
 * Provides cryptographically secure maintenance mode bypass mechanism with
 * comprehensive validation, logging, and audit trail capabilities.
 *
 * Security Features:
 * - Cryptographically random bypass tokens
 * - Time-limited token expiration
 * - Rate limiting on bypass attempts
 * - Audit logging of all bypass usage
 * - No hardcoded fallback values
 */

import crypto from "crypto";
import loggerInstance from "./logger";

const logger = loggerInstance;

/**
 * Maintenance Security Configuration
 * All values must come from environment variables
 */
function getTokenExpiryMinutes() {
  return parseInt(process.env.MAINTENANCE_TOKEN_EXPIRY_MINUTES || "60", 10);
}

const MAINTENANCE_CONFIG = {
  get TOKEN_EXPIRY_MINUTES() {
    return parseInt(process.env.MAINTENANCE_TOKEN_EXPIRY_MINUTES || "60");
  },
  get MAX_BYPASS_ATTEMPTS_PER_HOUR() {
    return parseInt(process.env.MAINTENANCE_MAX_ATTEMPTS_PER_HOUR || "10");
  },
  get REQUIRE_ADMIN_ROLE() {
    return process.env.MAINTENANCE_REQUIRE_ADMIN_ROLE === "true";
  },
};

/**
 * In-memory store for generated bypass tokens
 * In production, use Redis or database for distributed systems
 */
const bypassTokenStore = new Map();
const bypassAttemptLog = new Map();

/**
 * Generate a cryptographically secure bypass token
 *
 * @returns {Object} Token object with token string and expiration time
 */
export function generateBypassToken() {
  const token = crypto.randomBytes(32).toString("hex");
  const expiresAt = new Date(Date.now() + getTokenExpiryMinutes() * 60 * 1000);

  bypassTokenStore.set(token, {
    createdAt: new Date(),
    expiresAt,
    usedCount: 0,
  });

  logger.info("Generated new maintenance bypass token", {
    expiresAt: expiresAt.toISOString(),
    expiryMinutes: getTokenExpiryMinutes(),
  });

  return {
    token,
    expiresAt: expiresAt.toISOString(),
    expiryMinutes: getTokenExpiryMinutes(),
  };
}

/**
 * Verify a bypass token is valid and not expired
 *
 * @param {string} token - Token to verify
 * @returns {Object} Verification result with isValid and reason
 */
export function verifyBypassToken(token) {
  if (!token) {
    return {
      isValid: false,
      reason: "Token is required",
    };
  }

  const storedToken = bypassTokenStore.get(token);

  if (!storedToken) {
    logger.warn("Bypass token not found", {
      token: token.substring(0, 8) + "...",
    });
    return {
      isValid: false,
      reason: "Token not found or invalid",
    };
  }

  if (new Date() > storedToken.expiresAt) {
    logger.warn("Bypass token expired", {
      token: token.substring(0, 8) + "...",
    });
    bypassTokenStore.delete(token);
    return {
      isValid: false,
      reason: "Token has expired",
    };
  }

  storedToken.usedCount += 1;

  logger.info("Bypass token verified successfully", {
    token: token.substring(0, 8) + "...",
    usedCount: storedToken.usedCount,
  });

  return {
    isValid: true,
    reason: "Token is valid",
  };
}

/**
 * Check if user has exceeded bypass attempt rate limit
 *
 * @param {string} userId - User attempting bypass
 * @returns {boolean} True if rate limit exceeded
 */
function isRateLimited(userId) {
  const now = Date.now();
  const oneHourAgo = now - 60 * 60 * 1000;

  // Get attempt log for user
  if (!bypassAttemptLog.has(userId)) {
    bypassAttemptLog.set(userId, []);
  }

  const attempts = bypassAttemptLog.get(userId);

  // Remove old attempts outside one hour window
  const recentAttempts = attempts.filter((timestamp) => timestamp > oneHourAgo);

  if (
    recentAttempts.length >= MAINTENANCE_CONFIG.MAX_BYPASS_ATTEMPTS_PER_HOUR
  ) {
    logger.error("Rate limit exceeded for maintenance bypass", {
      userId,
      attemptCount: recentAttempts.length,
      limit: MAINTENANCE_CONFIG.MAX_BYPASS_ATTEMPTS_PER_HOUR,
    });
    return true;
  }

  recentAttempts.push(now);
  bypassAttemptLog.set(userId, recentAttempts);

  return false;
}

/**
 * Check if maintenance mode is active, with secure bypass verification
 *
 * @param {Object} request - Next.js request object
 * @param {string} userId - Current user ID for audit logging
 * @returns {boolean} True if maintenance mode is active
 */
export function isMaintenanceModeActive(request, userId = "unknown") {
  // Check if maintenance mode is enabled
  const isEnabled =
    process.env.NEXT_PUBLIC_MAINTENANCE_MODE === "true" ||
    process.env.NEXT_PUBLIC_MAINTENANCE_MODE === "1";

  if (!isEnabled) {
    return false;
  }

  if (!request) {
    return true; // No request object, assume maintenance mode active
  }

  // Check for bypass token in cookie or header
  const bypassTokenFromCookie = request.cookies?.get?.(
    "learnova_maintenance_bypass"
  )?.value;
  const bypassTokenFromHeader = request.headers?.get?.(
    "x-learnova-maintenance-bypass"
  );

  const bypassToken = bypassTokenFromCookie || bypassTokenFromHeader;

  if (!bypassToken) {
    // No bypass token provided, maintenance mode is active
    logger.debug("No bypass token provided", { userId });
    return true;
  }

  // Rate limit check
  if (isRateLimited(userId)) {
    logger.error("Maintenance bypass attempt rate limited", { userId });
    return true; // Enforce maintenance mode
  }

  // Verify bypass token
  const verification = verifyBypassToken(bypassToken);

  if (!verification.isValid) {
    logger.warn("Invalid maintenance bypass attempt", {
      userId,
      reason: verification.reason,
      source: bypassTokenFromCookie ? "cookie" : "header",
    });
    return true; // Enforce maintenance mode
  }

  // Bypass token is valid, maintenance mode is not active for this user
  logger.info("Maintenance mode bypassed for user", { userId });
  return false;
}

/**
 * Revoke a bypass token immediately
 *
 * @param {string} token - Token to revoke
 */
export function revokeBypassToken(token) {
  if (bypassTokenStore.has(token)) {
    bypassTokenStore.delete(token);
    logger.info("Bypass token revoked", {
      token: token.substring(0, 8) + "...",
    });
  }
}

/**
 * Clean up expired tokens (call periodically)
 */
export function cleanupExpiredTokens() {
  const now = new Date();
  let cleanedCount = 0;

  for (const [token, data] of bypassTokenStore.entries()) {
    if (now > data.expiresAt) {
      bypassTokenStore.delete(token);
      cleanedCount += 1;
    }
  }

  if (cleanedCount > 0) {
    logger.info("Cleaned up expired bypass tokens", { count: cleanedCount });
  }
}

/**
 * Get maintenance security status for monitoring/debugging
 *
 * @returns {Object} Current status information
 */
export function getMaintenanceStatus() {
  return {
    maintenanceEnabled: process.env.NEXT_PUBLIC_MAINTENANCE_MODE === "true",
    activeTokens: bypassTokenStore.size,
    trackedUsers: bypassAttemptLog.size,
    configuration: MAINTENANCE_CONFIG,
  };
}
